packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAgeExclude:
  - dsh-plugin-deepeye
  - '@linxin666/*'
allowBuilds:
  cloudflared: true
  cpu-features: true
  node-pty: true
  ssh2: true
