packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAgeExclude:
  - dsh-plugin-deepeye@0.1.1
  - '@linxin666/*'
allowBuilds:
  cloudflared: true
  cpu-features: true
  ssh2: true
